In [3]:
import pandas as pd

trainData = pd.read_csv('train.csv')
testData = pd.read_csv('test.csv')

y = trainData['Transported']
trainData.drop(['Transported','Name'],axis=1,inplace=True)

trainData.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0

In [4]:
for col in trainData.columns:
    try:
        print(col,y.corr(trainData[col]))
    except:
        print('Not valid right now for',col)

PassengerId 0.021491229884922664
Not valid right now for HomePlanet
CryoSleep 0.4686448608124055
Not valid right now for Cabin
Not valid right now for Destination
Age -0.07502558362232613
VIP -0.0376497222591982
RoomService -0.24461142158527566
FoodCourt 0.04656639376472204
ShoppingMall 0.01014089002427718
Spa -0.22113134924572825
VRDeck -0.20707538958428992

In [5]:
from sklearn.model_selection import train_test_split


missing_val_count_by_column = (trainData.isnull().sum())
print(missing_val_count_by_column[missing_val_count_by_column > 0])

HomePlanet      201
CryoSleep       217
Cabin           199
Destination     182
Age             179
VIP             203
RoomService     181
FoodCourt       183
ShoppingMall    208
Spa             183
VRDeck          188
dtype: int64

In [6]:

SetNullToZero = ['RoomService','FoodCourt','FoodCourt','ShoppingMall','Spa','VRDeck']
# Columns with 'Not Applicable'  in NaN
SetNullToNo = ['HomePlanet','Cabin','Destination']
#Columns with median in NaN
SetNullToMed = ['Age']
# Most Common
SetNullToMostFreq = ['CryoSleep','VIP']

In [7]:
trainData[SetNullToNo] = trainData[SetNullToNo].fillna(value = 'Not Applicable')
trainData[SetNullToMed] = trainData[SetNullToMed].fillna(trainData[SetNullToMed].median())
trainData[SetNullToZero] = trainData[SetNullToZero].fillna(0,inplace=True)
trainData[SetNullToMostFreq] = trainData[SetNullToMostFreq].fillna(value = trainData[SetNullToMostFreq].mode())

testData[SetNullToNo] = testData[SetNullToNo].fillna(value = 'Not Applicable')
testData[SetNullToMed] = testData[SetNullToMed].fillna(testData[SetNullToMed].median())
testData[SetNullToZero] = testData[SetNullToZero].fillna(0,inplace=True)
testData[SetNullToMostFreq] = testData[SetNullToMostFreq].fillna(value = testData[SetNullToMostFreq].mode())


X_train, X_valid, y_train, y_valid = train_test_split(trainData, y,
                                                    train_size=0.8, test_size=0.2,random_state=0)

X_train = pd.get_dummies(X_train)
X_valid = pd.get_dummies(X_valid)
X_test = pd.get_dummies(testData)
X_train, X_valid = X_train.align(X_valid, join='left', axis=1)
X_train, X_test = X_train.align(X_test, join='left', axis=1)
X_train.head(10)

C:\Users\shehr\AppData\Local\Temp\ipykernel_12968\638841136.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  trainData[SetNullToZero] = trainData[SetNullToZero].fillna(0,inplace=True)
C:\Users\shehr\AppData\Local\Temp\ipykernel_12968\638841136.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  testData[SetNullToZero] = testData[SetNullToZero].fillna(0,inplace=True)

,Age,PassengerId_0001_01,PassengerId_0002_01,PassengerId_0003_01,PassengerId_0003_02,PassengerId_0004_01,PassengerId_0005_01,PassengerId_0006_01,PassengerId_0006_02,PassengerId_0007_01,...,Cabin_T/1/P,Cabin_T/2/P,Cabin_T/2/S,Cabin_T/3/P,Destination_55 Cancri e,Destination_Not Applicable,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,VIP_False,VIP_True
4278,54.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
5971,20.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
464,43.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
4475,24.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
8469,25.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
557,48.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
3586,34.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
470,18.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False
4757,35.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
874,24.0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False

In [8]:
import numpy as np
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor


model = XGBRegressor(random_state = 0,n_estimators = 1000,learning_rate = 0.05,n_jobs = 4)

model.fit(X_train,y_train,early_stopping_rounds = 5,eval_set=[(X_valid,y_valid)],verbose = False) # Your code here

# Get predictions
predictions = np.rint(model.predict(X_valid)).astype(bool)

# Calculate MAE
# mae_3 = mean_absolute_error(predictions,y_valid)

# Uncomment to print MAE
# print("Mean Absolute Error:" , mae_3)
# predictions

ModuleNotFoundError: No module named 'xgboost'

In [64]:
final_predictions = np.rint(model.predict(X_test)).astype(bool)
# 0.4839385624704414
# X_test.head(10)
final_predictions

array([False,  True, False, ..., False,  True,  True])

In [65]:
output = pd.DataFrame({'PassengerId': testData.PassengerId,
                        'Transported': final_predictions})
output.to_csv('submission.csv', index=False)